name: EconomyPlugin
version: '0.0.1'
main: me.noklyf.economyplugin.EconomyPlugin
api-version: '1.20'

commands:
  pay:
    usage: /pay <player> <amount>
    description: Pays a certain amount to a player

  balance:
    usage: /balance
    description: Shows your current balance